name: .NET Build and Test

on:
  push:
    branches: ["development"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: "Calculate2025.sln"
    steps:
      - name: Checkout code
        uses: actions/checkout@v32

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --no-restore --verbosity normal
